spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.15/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

  jackson:
    default-property-inclusion: non_null
server:
  servlet.context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: F:/Download/BaiduNetdiskDownload/springboot_project/loginfo/
#  file: F:/Download/BaiduNetdiskDownload/springboot_project/sell.log
#  level:
#    LoggerTest: debug

wechat:
  mpAppId:
  mpAppSecret:
  mchId:
  mchKey:
  keyPath:
  notifyUrl: